version: "3"

services: 
  server:
    container_name: server
    build: ./server

  ocean:
    container_name: ocean 
    image: nginx:latest
    ports:
      - "80:8080"
    volumes: 
      - "./ocean/nginx.conf:/etc/nginx/nginx.conf"